const APP_URL = import.meta.env.VITE_APP_URL;

const API_PATH = "api";
const CREATE_CHALLENGE_METHOD = "create-challenge";

const API_URL = APP_URL + "/" + API_PATH;

export const CREATE_CHALLENGE_URL = API_URL + "/" + CREATE_CHALLENGE_METHOD;

const CONTEXT_SCHEME = "https";
const CONTEXT_THIRD_DOMAIN = "context";
const CONTEXT_SECOND_DOMAIN = "maergroup";
const CONTEXT_FIRST_DOMAIN = "ru";
const CONTEXT_API_PATH = "api";
const CONTEXT_DOMAINS = CONTEXT_THIRD_DOMAIN + "." + CONTEXT_SECOND_DOMAIN + "." + CONTEXT_FIRST_DOMAIN;
const CONTEXT_API_URL = CONTEXT_SCHEME + "://" + CONTEXT_DOMAINS + "/" + CONTEXT_API_PATH;

export const CONTEXT_API_URLS_PATTERN = CONTEXT_API_URL + "/" + "*";
